#!/bin/bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "${DIR}/config_remote.sh"

PACKAGE_BUILD_DIR="${DIR}/package_build"
PACKAGE_FILE="${PACKAGE_BUILD_DIR}/todos.xz.run"

rsync --archive --recursive --delete \
    --exclude "vendor" \
    "${DIR}/../src" "${DIR}/package/"

(cd "${DIR}/package/src" && composer install)

mkdir --parents "${PACKAGE_BUILD_DIR}"
makeself --xz "${DIR}/package" "${PACKAGE_FILE}" "Todo Service" ./install
REMOTE_CMD='cat - > /root/package && chmod +x /root/package && /root/package'
ssh "root@${HOST}" -- "${REMOTE_CMD}" < "${PACKAGE_FILE}"
