#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "${DIR}/config_remote.sh"


scp "${DIR}/provision_remote.d/todos" root@$HOST:/etc/nginx/sites-available/todos

ssh root@$HOST -- mkdir --parent /var/www/todos
ssh root@$HOST -- ln --force --symbolic /etc/nginx/sites-available/todos /etc/nginx/sites-enabled/todos
ssh root@$HOST -- rm --force /etc/nginx/sites-enabled/default
ssh root@$HOST -- service nginx reload

rsync --archive --recursive --delete "${DIR}/.." root@$HOST:/var/www/todos
