#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "${DIR}/config_remote.sh"


ssh root@$HOST -- env DEBIAN_FRONTEND=noninteractive apt-get update
ssh root@$HOST -- env DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

# Configuration file '/etc/cloud/cloud.cfg'
#  ==> Modified (by you or by a script) since installation.
#  ==> Package distributor has shipped an updated version.
#    What would you like to do about it ?  Your options are:
#     Y or I  : install the package maintainer's version
#     N or O  : keep your currently-installed version
#       D     : show the differences between the versions
#       Z     : start a shell to examine the situation
#  The default action is to keep your current version.
# *** cloud.cfg (Y/I/N/O/D/Z) [default=N] ? Y

# OpenSSH? Install mainteiner version

ssh root@$HOST -- env DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y
ssh root@$HOST -- apt-get install -y nginx
ssh root@$HOST -- apt-get install -y php-fpm
