#!/bin/bash

REMOTE_HOST=188.68.220.222

ssh root@$REMOTE_HOST -- env DEBIAN_FRONTEND=noninteractive apt-get update
ssh root@$REMOTE_HOST -- env DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

# Configuration file '/etc/cloud/cloud.cfg'
#  ==> Modified (by you or by a script) since installation.
#  ==> Package distributor has shipped an updated version.
#    What would you like to do about it ?  Your options are:
#     Y or I  : install the package maintainer's version
#     N or O  : keep your currently-installed version
#       D     : show the differences between the versions
#       Z     : start a shell to examine the situation
#  The default action is to keep your current version.
# *** cloud.cfg (Y/I/N/O/D/Z) [default=N] ? Y

# OpenSSH? Install mainteiner version

ssh root@$REMOTE_HOST -- env DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y
ssh root@$REMOTE_HOST -- apt-get install -y nginx
ssh root@$REMOTE_HOST -- apt-get install -y php-fpm
